using System;

namespace CSharpDay4Project
{
    class ExceptionHandlingDemo3
    {
        //static void Main(string[] args)
        //{
        //    int num1, num2, result = 0;
        //    try
        //    {
        //        Console.WriteLine("enter first number");
        //        num1 = int.Parse(Console.ReadLine());
        //        Console.WriteLine("enter second number");
        //        num2 = int.Parse(Console.ReadLine());
        //        result = num1 / num2;
        //        //Console.WriteLine("Result : " + result);
        //    }
        //    catch(ArithmeticException ex)
        //    {
        //        Console.WriteLine("Catch Block 1: " + ex.Message);
        //    }
        //    catch (IndexOutOfRangeException ex)
        //    {
        //        Console.WriteLine("Catch Block 2:" + ex.Message);
        //    }
        //    catch (Exception ex)
        //    {
        //        Console.WriteLine("Catch Block 3:" + ex.Message);
        //    }
        //    finally
        //    {
        //        Console.WriteLine("Result : " + result);

        //    }
        //    Console.ReadKey();
        //}
    }
}
